# Generated by Django 3.2.4 on 2021-07-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodalert.userprofile')),
            ],
        ),
    ]
