# Generated by Django 3.2.4 on 2021-07-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='location_or_Description',
        ),
    ]
