# Generated by Django 3.2.4 on 2021-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0003_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.TextField(default='2nd Avenue Karuturi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
