# Generated by Django 3.2.4 on 2021-07-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0003_rename_location_business_location_or_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='description',
        ),
    ]
