# Generated by Django 3.2.4 on 2021-07-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0004_rename_post_posts_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id']},
        ),
    ]
