# Generated by Django 3.2.4 on 2021-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodalert', '0004_auto_20210725_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
